name: Deploy

# Trigger the workflow on push and 
# pull request events on the production branch
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD_SERVER
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /srv/users/auctionit/apps/auctionit && sudo bash .scripts/deploy.sh"